export const images = [
  { id: 1, path: "/demo/1.jpg" },
  { id: 2, path: "/demo/2.jpg" },
  { id: 3, path: "/demo/3.jpg" },
  { id: 4, path: "/demo/4.jpg" },
  { id: 5, path: "/demo/5.jpg" },
  { id: 6, path: "/demo/6.jpg" },
  { id: 7, path: "/demo/7.jpg" },
  { id: 8, path: "/demo/8.jpg" },
  { id: 9, path: "/demo/9.jpg" },
  { id: 10, path: "/demo/10.jpg" },
  { id: 11, path: "/demo/11.jpg" },
  { id: 12, path: "/demo/12.jpg" },
  { id: 13, path: "/demo/13.jpg" },
  { id: 14, path: "/demo/14.jpg" },
  { id: 15, path: "/demo/15.jpg" },
  { id: 16, path: "/demo/16.jpg" },
  { id: 17, path: "/demo/17.jpg" },
  { id: 18, path: "/demo/18.jpg" },
  { id: 19, path: "/demo/19.jpg" },
  { id: 20, path: "/demo/20.jpg" },
  { id: 21, path: "/demo/21.jpg" },
  { id: 22, path: "/demo/22.jpg" },
  { id: 23, path: "/demo/23.jpg" },
  { id: 24, path: "/demo/24.jpg" },
  { id: 25, path: "/demo/25.jpg" },
  { id: 26, path: "/demo/26.jpg" },
  { id: 27, path: "/demo/27.jpg" },
  { id: 28, path: "/demo/28.jpg" },
  { id: 29, path: "/demo/29.jpg" },
  { id: 30, path: "/demo/30.jpg" },
  { id: 31, path: "/demo/31.jpg" },
  { id: 32, path: "/demo/32.jpg" },
  { id: 33, path: "/demo/33.jpg" },
  { id: 34, path: "/demo/34.jpg" },
  { id: 35, path: "/demo/35.jpg" },
  { id: 36, path: "/demo/36.jpg" },
  { id: 37, path: "/demo/37.jpg" },
  { id: 38, path: "/demo/38.jpg" },
  { id: 39, path: "/demo/39.jpg" },
  { id: 40, path: "/demo/40.jpg" },
  { id: 41, path: "/demo/41.jpg" },
  { id: 42, path: "/demo/42.jpg" },
  { id: 43, path: "/demo/43.jpg" },
  { id: 44, path: "/demo/44.jpg" },
  { id: 45, path: "/demo/45.jpg" },
  { id: 46, path: "/demo/46.jpg" },
  { id: 47, path: "/demo/47.jpg" },
  { id: 48, path: "/demo/48.jpg" },
  { id: 49, path: "/demo/49.jpg" },
  { id: 50, path: "/demo/50.jpg" },
  { id: 51, path: "/demo/51.jpg" },
  { id: 52, path: "/demo/52.jpg" },
  { id: 53, path: "/demo/53.jpg" },
  { id: 54, path: "/demo/54.jpg" },
  { id: 55, path: "/demo/55.jpg" },
];

export const BenefitsArray = [
  {
    id: 1,
    image: "/benefit/fast.png",
    headline: "Faster Initial Load",
    description:
      "Rendering components on the server side results in better SEO and faster initial page loads because the HTML is pre-generated and sent to the client.",
  },
  {
    id: 2,
    image: "/benefit/smaller.png",
    headline: "Smaller Initial Bundle Sizes",
    description:
      "Automatic code splitting optimizes performance by loading only necessary JavaScript code, reducing initial load times.",
  },
  {
    id: 3,
    image: "/benefit/route.png",
    headline: "Effortless Page Routing",
    description:
      "A built-in routing system simplifies dynamic client-side navigation without the need for external routing libraries.",
  },
  {
    id: 4,
    image: "/benefit/server.png",
    headline: "Seamless Backend Integration",
    description:
      "Serverless API routes can be defined within your app, enabling effortless integration with backend services and APIs.",
  },
  {
    id: 5,
    image: "/benefit/structure.png",
    headline: "Intuitive Project Structure",
    description:
      "Utilizing a file-based routing approach, where each page corresponds to a file, makes project structure and navigation intuitive.",
  },
  {
    id: 6,
    image: "/benefit/lightning.png",
    headline: "Lightning-Fast Pre-rendered Pages",
    description:
      "Support for static site generation allows for pre-rendering static pages at build time, resulting in fast page loads and reduced server load.",
  },

  {
    id: 7,
    image: "/benefit/seo.png",
    headline: "Improved SEO",
    description:
      "Rendering components on the server side results in better SEO because the HTML is pre-generated and sent to the client.",
  },
  {
    id: 8,
    image: "/benefit/render.png",
    headline: "Hybrid Rendering",
    description:
      "Mix server-side rendering and static site generation in a single app, choosing the best approach for each page.",
  },
];
